/*
 * ExceptionExample:
 * 
 * Demonstrates how to catch a NumberFormatException generated by Integer.parseInt(String),
 * 	then throw an IllegalFormatException.
 * 
 * See the HW Help video for a discussion of the below code.
 * 
 * Use the ideas herein to help with Problem 4 of HW 2.
 * 
 */
public class ExceptionExample
{
	public static void main (String[] args)
	{
		StdOut.print ("Enter an integer to parse: ");
		String numStr = StdIn.readString();
		
		int num = 0;
		
		try
		{
			num = Integer.parseInt(numStr);
		}
		catch (NumberFormatException e)
		{
			StdOut.printf("Note how num's value stays at initial 0 value: %d\n\n",  num);
			StdOut.printf ("'%s' is not a valid int.  Throwing IllegalArgumentException...\n\n", numStr);
			
			throw new IllegalArgumentException("bad int format");
		}
		
		StdOut.printf("You entered %d\n",  num);
	}
	
}
